### ISSUE TITLE
Installing Lumen at common server

### ISSUE THREAD

**Issue by the-infinity** [wordsandwriting/lumen#19]
Hi, everyone,

because my customers organization has a common server I tried to install Lumen at this server instead of a digitalocean server. I'm quite new to rails (more the python guy), so I may made mistakes. What I did:
- upgraded to Ubuntu 16.04 in order to get the required ruby 2.3
- cloned everything
- installed all gems locally
- installed unicorn
- created an supervisord config file
- set all the enviroment variables
- set up nginx as reverse proxy
- installed mongodb
- run all the required and cronjob rake commands (which work without errors)

It works so far: https://network.euroalter.com/ - but: as soon as you try to submit any data you got logged out. The data is not saved.

Supervisords logs are empty. Unicorn logs that somehow an http 302 was generated, but no more information. I did not find a way to do more logging inside the app.

So the question it: what does cause this behaviour?

If I got through all this, you can expect a mini-howto for installing Lumen at common servers. ;)

**Comment by the-infinity** [comment]
Quite interesting (don't know if related) error:
$ /srv/www/com.euroalter.network/httpdocs/vendor/bundle/ruby/2.3.0/bin/padrino c
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'padrino-core' (>= 0.a) among 76 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/euroalter-network/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /srv/www/com.euroalter.network/httpdocs/vendor/bundle/ruby/2.3.0/bin/padrino:22:in `<main>'

Here's my environment:
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/euroalter-network/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/euroalter-network/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /home/euroalter-network/.gem/ruby/2.3.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /snap/bin

Perhaps also interesting is this (no padrino?):
$ gem list

*** LOCAL GEMS ***

actionmailer (4.2.6)
actionpack (4.2.6)
actionview (4.2.6)
activejob (4.2.6)
activemodel (4.2.6)
activerecord (4.2.6)
activesupport (4.2.6)
arel (6.0.3)
atomic (1.1.16)
bigdecimal (1.2.8)
binding_of_caller (0.7.2)
blankslate (3.1.3)
builder (3.2.2)
bundle (0.0.1)
bundler (1.13.1, 1.11.2)
byebug (5.0.0)
coffee-rails (4.1.0)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
columnize (0.9.0)
debug_inspector (0.0.2)
did_you_mean (1.0.0)
erubis (2.7.0)
execjs (2.6.0)
ffi (1.9.10)
globalid (0.3.6)
hike (1.2.1)
i18n (0.7.0)
io-console (0.4.5)
jbuilder (2.3.1)
jquery-rails (4.0.5)
json (1.8.3)
kgio (2.10.0)
listen (3.0.3)
loofah (2.0.3)
mail (2.6.3)
mime-types (2.6.1)
minitest (5.8.4)
molinillo (0.4.3)
multi_json (1.11.2)
net-http-persistent (2.9.4)
net-telnet (0.1.1)
nokogiri (1.6.7.2)
oj (2.12.10)
polyglot (0.3.4)
power_assert (0.2.7)
psych (2.0.17)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.6)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.6)
rails-html-sanitizer (1.0.3)
railties (4.2.6)
raindrops (0.16.0)
rake (10.5.0)
rb-inotify (0.9.7)
rdoc (4.2.1)
sass (3.4.21)
sass-rails (5.0.4)
sdoc (0.4.1)
spring (1.3.6)
sprockets (3.3.0)
sprockets-rails (2.3.2)
sqlite3 (1.3.11)
test-unit (3.1.7)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.1)
treetop (1.6.3)
turbolinks (2.5.3)
tzinfo (1.2.2)
uglifier (2.7.2)
unicorn (4.9.0)
web-console (2.2.1)
